### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by keflavich** [radio-astro-tools/uvcombine#3]
Things we want to implement: (@baobabyoo, @esoPanda)

Plot routines:
* [ ] amplitude vs UV distance 
* [ ] Weighting as a function of UV distance
* [ ] Power spectral density image (abs(fft) image)

Features to implement:
* [ ] immerge "feather" scaling
* [ ] immerge-style weighting with convolved hi+lo res beams
* [ ] Noise estimation (?)
